//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular4.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerDetail
    {
        public int customerId { get; set; }
        public string name { get; set; }
        public string emailId { get; set; }
        public string phoneNumber { get; set; }
        public string message { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string address { get; set; }
    }
}
